bow:
  type: "BOW"
  name: "<aqua><bold>Teleport</bold><dark_aqua><bold>Bow</bold>"
  lore:
    - "<gray>Shoot an arrow to teleport"
  slot: 0
  arrow-slot: 9
  arrow-damage: false
  needed-permission: false
  give-on-join: true
  can-be-moved-in-inventory: true
  can-be-dropped: true
  can-be-swapped: true

worlds:
  # whitelist - Allow only worlds in this list
  # blacklist - Deny only worlds in this list
  # none - do nothing
  list-type: none
  list:
    - world
    - world_nether

# This section need WorldGuard plugin
regions:
  # whitelist - Allow only regions in this list
  # blacklist - Deny only regions in this list
  # none - do nothing
  list-type: none
  list:
    - region

teleport:
  sound:
    # Sound list:
    # https://pck.li/sounds
    type: "ENTITY_ENDERMAN_TELEPORT"
    volume: 1.0
    pitch: 1.0
    enable: true

message:
  prefix: "<gray>[<bold><aqua>Teleport</aqua><dark_aqua>Bow</dark_aqua></bold>]"
  reload: "<dark_green>Plugin reload!"
  no-console: "<red>You cannot run this command!"
  no-perm: "<red>You do not have the permission!"
  usage: "<green>Usage:"
  player-not-found: "<red>The player <gray>{player} <red>does not exists"
  world-not-allowed: "<red>The Bow in this world is not allowed"
  region-not-allowed: "<red>The Bow in this region is not allowed"
  bow-not-allowed: "<red>You can't use this bow"

check-for-updates: true

bstats: true